### PR TITLE
Add support for structs as decision arguments

### PR DESCRIPTION
**Pull request by laszloesl**
We're experimenting with the library and we'd like to use it with Ecto structs.

Rather than having to convert all struct recursively to maps, I propose to handle this in the library while building the context.

### CODE REVIEW

**Comment by laszloesl** [comment]
@devstopfix also let me know your thoughts. Went for a compact but safe implementation.

**Comment by devstopfix** [comment]
> @devstopfix also let me know your thoughts. Went for a compact but safe implementation.

Thanks @laszloesl - looks good - the only alternative would be that we would need to implement Access on all our structs, of which we will have many I believe?

**Comment by laszloesl** [comment]
> > @devstopfix also let me know your thoughts. Went for a compact but safe implementation.
> 
> Thanks @laszloesl - looks good - the only alternative would be that we would need to implement Access on all our structs, of which we will have many I believe?

yeah, I'd prefer if we didn't have to do that.

**Comment by qhwa** [comment]
LGTM

**Comment by qhwa** [comment]
This PR will be released in the next version (0.2.0).

**Pull request merged**
